syntax = "proto3";

package file.v1;

option go_package = "github.com/Garryflop/DormOS-gen-go/file/v1;filev1";

service FileService {
  rpc UploadFile(stream UploadFileRequest) returns (UploadFileResponse);
  rpc GetFileURL(GetFileURLRequest) returns (GetFileURLResponse);
  rpc DeleteFile(DeleteFileRequest) returns (DeleteFileResponse);
}

message UploadFileRequest {
  oneof request {
    FileMetadata metadata = 1;
    bytes chunk_data = 2;
  }
}

message FileMetadata {
  string filename = 1;
  string content_type = 2;
}

message UploadFileResponse {
  string file_id = 1;
  string url = 2;
}

message GetFileURLRequest {
  string file_id = 1;
}

message GetFileURLResponse {
  string url = 1;
}

message DeleteFileRequest {
  string file_id = 1;
}

message DeleteFileResponse {
  bool success = 1;
}
